name: flutter_task
description: "Flutter task"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
